name: Decomission Infra using Terraform
on:
  workflow_dispatch:
jobs:
  destroy-infra:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Destroy
        run: terraform destroy -auto-approve
        working-directory: infra
