name: Deploy React app
on:
  workflow_dispatch:
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      TF_VAR_key_name: ${{ secrets.TF_VAR_key_name }}
    steps:
      - name: Checkout Repo Content
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ env.AWS_REGION }}

      - name: Get required parameters
        id: get-paramters
        run: |
          EC2_INSTANCE_ID=$(aws ssm get-parameter \
                                --name "/devops/react-site-ec2-instance-id" \
                                --query "Parameter.Value" \
                                --output text)
          echo "ec2_instance_id=$EC2_INSTANCE_ID" >> $GITHUB_OUTPUT

          ECR_REGISTRY_URL=$(aws ssm get-parameter \
                                --name "/devops/ecr-registry_url" \
                                --query "Parameter.Value" \
                                --output text)

          echo "ecr_registry_url=$ECR_REGISTRY_URL" >> $GITHUB_OUTPUT

          ECR_REPO_NAME=$(aws ssm get-parameter \
                                --name "/devops/ecr-repo-name" \
                                --query "Parameter.Value" \
                                --output text)

            echo "ecr_repo_name=$ECR_REPO_NAME" >> $GITHUB_OUTPUT

      - name: Generate pre-signed URL
        id: presign-url
        run: |
          URL=$(aws s3 presign s3://adi-s3-bucket-01/latest-builds/react-app-latest.tar --expires-in 900)

          sudo apt-get install -y dos2unix
          sudo dos2unix ./scripts/*
          
          ESCAPED_URL=$(printf '%s\n' "$URL" | sed 's/[&/\]/\\&/g')
          sed -i -e "s|__signed_url__|$ESCAPED_URL|g" ./scripts/setup-react-app.sh
          sed -i -e "s|__image_repo_url__|${{ steps.get-paramters.outputs.ecr_registry_url }}|g" ./scripts/setup-react-app.sh
          sed -i -e "s|__image_name__|${{ steps.get-paramters.outputs.ecr_repo_name }}|g" ./scripts/setup-react-app.sh
            
          cat ./scripts/setup-react-app.sh

      - name: Deploy build
        run: |
          SCRIPT_CONTENT=$(jq -Rc . < scripts/setup-react-app.sh | jq -s .)

          aws ssm send-command \
            --document-name "AWS-RunShellScript" \
            --comment "Setup" \
            --targets "Key=instanceIds,Values=${{ steps.get-paramters.outputs.ec2_instance_id }}" \
            --parameters "commands=$SCRIPT_CONTENT"  \
            --region ${{ env.AWS_REGION}}
